# Generated by Django 5.2.7 on 2025-10-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='social_media_handle',
        ),
        migrations.AddField(
            model_name='influencer',
            name='bio_videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='influencer',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Travel', 'Travel'), ('Comedy', 'Comedy'), ('Sports', 'Sports'), ('Entrepreneurship', 'Entrepreneurship'), ('Gaming', 'Gaming')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_acc_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_profiles/'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='snapchat_acc_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_acc_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_acc_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
