# Generated by Django 5.2.7 on 2025-10-22 20:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_client_address_remove_client_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='bio_videos',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='daily_price',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='instagram_acc_link',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='snapchat_acc_link',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='tiktok_acc_link',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='weekly_price',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='youtube_acc_link',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='influencer',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='social_media_handle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
