# Generated by Django 5.2.7 on 2025-10-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_client_address_remove_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN no spaces, uppercase', max_length=34, null=True),
        ),
    ]
